version: 2.1
jobs:
  install-and-test:
    docker:
      - image: cimg/python:3.11
      - image: circleci/redis:5.0.0
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install pytest mock
      - run: py.test
workflows:
  test:
    jobs:
      - install-and-test
