version: 2.1
jobs:
  install-and-test:
    docker:
      - image: cimg/python:3.11
      - image: circleci/redis:5.0.0
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y python3-setuptools && sudo python3 setup.py install
      - run: pip3 install pytest mock redis==4.5.2
      - run: py.test
workflows:
  test:
    jobs:
      - install-and-test
