version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.5.9
      - image: circleci/redis:5.0.0
    steps:
      - checkout
      - run: python setup.py install
      - run: pip install pytest mock
      - run: py.test
workflows:
  test:
    jobs:
      - test
